services:
  - type: web
    name: teams-gateway
    env: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: BACKEND_URL
        value: https://admin-assistant-npsd.onrender.com
      - key: MICROSOFT_APP_ID
        sync: false
      - key: MICROSOFT_APP_PASSWORD
        sync: false
